name: shopping_store
description: An e-commerce application.

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  http: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.1
  loader_overlay: ^2.3.2
  flutter_spinkit: ^5.2.0
  flutter_localization: ^0.1.13
  flutter_svg: ^2.0.7
  stylish_bottom_bar: ^1.0.3
  flutter_expanded_tile: ^0.3.7
  bot_toast: ^4.1.3
  proste_bezier_curve: ^2.0.2
  card_swiper: ^3.0.1
  photo_view: ^0.14.0
  chewie: ^1.7.1
  video_player: ^2.7.2
  url_launcher: ^6.1.14
  custom_refresh_indicator: ^2.2.1
  sign_button: ^2.0.6
  otp_text_field: ^1.1.3
  visibility_detector: ^0.4.0+2
  page_view_dot_indicator: ^2.3.0
  flutter_advanced_switch: ^3.0.1
  animated_custom_dropdown: ^1.5.0
  myfatoorah_flutter: ^3.0.3
  popup_menu_plus: ^0.0.6
  intl: ^0.18.1
  easy_stepper: ^0.8.1
  flutter_profile_picture: ^2.0.0
  image_picker: ^1.0.4
  google_sign_in: ^6.1.5
  firebase_core: ^2.18.0
  firebase_auth: ^4.11.0
  flutter_facebook_auth: ^6.0.2
  sign_in_with_apple: ^5.0.0
  adaptive_dialog: ^1.9.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/png/
    - assets/jpg/
  fonts:
    - family: Mooli
      fonts:
        - asset: assets/fonts/mooli/Mooli-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
        - asset: assets/fonts/roboto/Roboto-Light.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 23
